In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mt

In [10]:
''' (1) Convert a 1D array to a 2D array with 2 rows'''

array_1d = np.array([1, 2, 3, 4, 5, 6])
array_2d = array_1d.reshape(2,3)
print(array_2d)


[[1 2 3]
 [4 5 6]]


In [11]:
''' () Get the common items between a and b'''

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

common_items = np.intersect1d(a,b)
print(common_items)

[2 4]


In [12]:
''' (3) Get all items between 5 and 10 from a'''

a = np.array([2, 6, 1, 9, 10, 3, 27])
items = a[(a >= 5) & (a <= 10)]
print(items)


[ 6  9 10]


In [13]:
''' (4) Limit the number of items printed in a NumPy array to a maximum of 6 elements'''

a = np.arange(15)
np.set_printoptions(threshold=6)
print(a)

[ 0  1  2 ... 12 13 14]
